name: EPG Service

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (9:00am IST)
  push:
    branches: [ main ]

jobs:
  epg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests xmltodict
      - name: Get EPG Data
        run: python ./python/epg.py ./python/epg.xml ./python/epg.xml.gz
      - name: Commit updated epg.xml
        run: |
          git config --global user.name 'krreet'
          git commit -am "Automated EPG"
          git push
