name: EPG Service

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (9:00am IST)

jobs:
  epg:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests xmltodict
      - name: Get EPG Data
        run: python ./python/epg.py ./python/epg.xml.gz
      - name: Commit updated epg.xml
      - name: Commit updated epg.xml
        run: |
          git pull
        # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated EPG
