name: Purge epg

on:
  workflow_dispatch:

jobs:
  epg:
    runs-on: ubuntu-latest

    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/krreet/epg/python/epg.xml.gz
            https://cdn.jsdelivr.net/gh/krreet@main/epg/python/epg.xml.gz
